### ISSUE TITLE
Typo in "How to setup a Nethermind only Spaceneth based chain"?

### ISSUE THREAD

**Issue by xJonathanLEI** [NethermindEth/docs#21]
From `ethereum-client/private-networks/how-to-setup-a-nethermind-only-spaceneth-based-chain.md`:

* download [chainspec](https://raw.githubusercontent.com/NethermindEth/nethermind/master/src/Nethermind/Chains/spaceneth.json) file with **clique** engine and place it in `genesis` folder.

Should be **spaceneth** engine?

**Comment by SebastianDremo** [comment]
Yes, thank you for your help
